export { default as NavBar } from './NavBar';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as Contact } from './Contact';
export { default as Hero } from './Hero'
export { default as Footer } from './Footer'
export { default as Info } from './Info'
export { default as Tools } from './Tools'
export { default as Industries } from './Industries'
export { default as Portfolio } from './Portfolio'
export { default as Testimonials } from './Testimonials'
